#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DeliveryPersonApp.Droid.Resource", IsApplication=true)]

namespace DeliveryPersonApp.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "13.1.0.5")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int ic_action_add = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int ic_action_home = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int ic_action_list = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int ic_action_map = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int ic_action_person = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F030009
			public const int icon = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int icon_round = 2130903050;
			
			// aapt resource value: 0x7F030000
			public const int ic_action_add = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int ic_action_home = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int ic_action_list = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int ic_action_map = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int ic_action_person = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int ic_launcher = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int ic_launcher_background = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int ic_launcher_foreground = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int ic_launcher_monochrome = 2130903048;
			
			// aapt resource value: 0x7F03000B
			public const int launcher_foreground = 2130903051;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F040000
			public const int MainTheme = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F050000
			public const int file_paths = 2131034112;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
